# Copyright 2019 The Scheduler Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

version: '3'

services:
  scheduler-etcd:
    image: "quay.io/coreos/etcd:v3.2.18"
    command: etcd --data-dir /data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://scheduler-etcd:2379 --max-snapshots 5 --max-wals 5 --auto-compaction-retention=168
    volumes:
      - ${DATA_PATH}/etcd:/data
    ports:
     - "12379:2379" # for unit-test & debug
    container_name: "scheduler-etcd"
    logging:
      driver: "json-file"
      options:
        max-size: ${SCHEDULER_LOG_MAX_SIZE}
        max-file: ${SCHEDULER_LOG_MAX_FILE}

  scheduler-apiserver:
    container_name: "scheduler-apiserver"
    image: "scheduler:latest"
    command: "/scheduler/apiserver"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - scheduler-etcd
    environment:
      - SCHEDULER_LOG_LEVEL=${SCHEDULER_LOG_LEVEL}
      - SCHEDULER_ETCD_ENDPOINTS=${ETCD_ENDPOINTS}
    logging:
      driver: "json-file"
      options:
        max-size: ${SCHEDULER_LOG_MAX_SIZE}
        max-file: ${SCHEDULER_LOG_MAX_FILE}

  scheduler-nodeagent:
    container_name: "scheduler-nodeagent"
    image: "scheduler:latest"
    command: "/scheduler/nodeagent"
    links:
      - scheduler-apiserver:scheduler-apiserver
    depends_on:
      - scheduler-apiserver
    environment:
      - SCHEDULER_LOG_LEVEL=${SCHEDULER_LOG_LEVEL}
      - SCHEDULER_API_SERVER_API_HOST=${SCHEDULER_API_SERVER_API_HOST}
      - SCHEDULER_API_SERVER_API_PORT=${SCHEDULER_API_SERVER_API_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: ${SCHEDULER_LOG_MAX_SIZE}
        max-file: ${SCHEDULER_LOG_MAX_FILE}

  scheduler-scheduler:
    container_name: "scheduler-scheduler"
    image: "scheduler:latest"
    command: "/scheduler/scheduler"
    links:
      - scheduler-apiserver:scheduler-apiserver
    depends_on:
      - scheduler-apiserver
    environment:
      - SCHEDULER_LOG_LEVEL=${SCHEDULER_LOG_LEVEL}
      - SCHEDULER_API_SERVER_API_HOST=${SCHEDULER_API_SERVER_API_HOST}
      - SCHEDULER_API_SERVER_API_PORT=${SCHEDULER_API_SERVER_API_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: ${SCHEDULER_LOG_MAX_SIZE}
        max-file: ${SCHEDULER_LOG_MAX_FILE}

  scheduler-controller:
    container_name: "scheduler-controller"
    image: "scheduler:latest"
    command: "/scheduler/controller"
    links:
      - scheduler-apiserver:scheduler-apiserver
    depends_on:
      - scheduler-apiserver
    environment:
      - SCHEDULER_LOG_LEVEL=${SCHEDULER_LOG_LEVEL}
      - SCHEDULER_API_SERVER_API_HOST=${SCHEDULER_API_SERVER_API_HOST}
      - SCHEDULER_API_SERVER_API_PORT=${SCHEDULER_API_SERVER_API_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: ${SCHEDULER_LOG_MAX_SIZE}
        max-file: ${SCHEDULER_LOG_MAX_FILE}
